project:
  type: website

website:
  title: "Alice Tivarovsky"
  description: "I created this blog to explore health topics, deepen programming and data skills, showcase projects, and document useful tidbits I learned along the way."
  site-url: "https://www.alicetivarovsky.com"
  favicon: favicon.png
  page-footer:
    left: |
      © 2020-<span id="copyright-year"></span> Alice Tivarovsky
      <script>
        document.getElementById("copyright-year").textContent = new Date().getFullYear();
      </script>
  navbar:
    left:
    - icon: linkedin
      href: https://www.linkedin.com/in/alicetivarovsky/
      aria-label: LinkedIn
    - icon: github
      href: https://github.com/ativarovsky
      aria-label: GitHub
    right:
      - text: "Blog"
        href: blog.qmd
      - about.qmd

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css

resources:
  - _redirects
