baseurl = "/"
title = "Alice Tivarovsky"
author = "Alice Tivarovsky"
canonifyurls = "yes"
languagecode = "en"
paginate = 3
theme = "hugo-renga"
enableEmoji = "yes"
hasCJKLanguage = "yes"
ignoreFiles = [ "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$" ]

[params]
copyright = "© 2020-2023 Alice Tivarovsky"
copyrightUrl = "/"
email = "ativarovsky@gmail.com"
faviconfile = "image/avatar.png"
github = "ativarovsky"
highlightjs = true
linkedin = "alicetivarovsky"
logofile = "image/IMG_2421.png"
pagetitle = "Alice Tivarovsky"
posts_navigation = true
progressively = false
twitter = "ativarovsky"
uselatex = true
latestpostcount = 7

[[menu.primary]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.primary]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 2

[[menu.primary]]
identifier = "tags"
name = "Posts by Tag"
url = "/tags/"
weight = 3

[[menu.primary]]
identifier = "resources"
name = "Useful Resources"
url = "/resources/"
weight = 4

[permalinks]
    post = "/:year/:month/:day/:slug/"
