---
title: "About"
author: "Alice Tivarovsky"
date: '2022-09-02'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Below is a snapshot of my career thus far. The journey has been, shall we say, non-linear. But good stories always have some plot twists and turns. Today, I feel fortunate to work in a highly visible field, where I get to play with data, help policy-makers make decisions, and, with hope, leave a positive impact in the community. 

For more details, please find me on [LinkedIn](https://www.linkedin.com/in/alice-tivarovsky-56281131/). 

***
### Education

- University of California, Los Angeles | BS, Chemical Engineering
- Columbia University | MPH, Epidemiology &  Applied Biostatistics

***

### Professional

#### Senior Analyst, Data Science | Sep 2023 - Present | AltaMed Healthcare
- Built data tools (SQL/Tableau, R/RStudio) to support clinicians in population health analysis
- Validated probability models in predictive accuracy of emergency room and inpatient hospital utilization
- Designed and implemented program evaluation framework to measure ROI of large-scale telehealth program
- Built datasets and visualization tools to analyze utilization and cost in special cohorts (e.g. oncology patients)

#### Data Science Epidemiologist | Jan 2023 - Sep 2023 | Washington State Department of Health 
- Quantified burden of Covid-19 using big data tools (Spark/DataBricks)

#### Epidemiologist (Covid-19 Response) | Feb 2022 - Jan 2023 | Los Angeles County Department of Public Health  
- Cleaned, analyzed, and managed all data received by the Education Sector on a daily basis (n = 500k)
- Wrote, validated, and optimized data management and analysis programs using R, SQL, and SAS
- Produced and maintained all unit data products, including public-facing [TK-12 School Covid-19 Data Dashboard](http://publichealth.lacounty.gov/media/coronavirus/education/index.htm) and internal Covid-19 report, containing summaries and in-depth analyses of all case data reported to Education Sector, for use by Public Health leadership
- Served as supervisor for Epi Analyst

#### Epidemiology Data Analyst (Covid-19 Response) | Sep 2020 - Feb 2022 | Los Angeles County Department of Public Health  
- Built Covid-19 dashboards and reports using SAS and R; optimized programs and performed troubleshooting
- Investigated and supported containment of Covid-19 outbreaks in universities

#### Lead Teaching Assistant | Sep 2019 - May 2020 | Columbia University Mailman School of Public Health
-	Supported faculty in developing lecture materials, homework assignments, and exams for Quantitative Research Methods and Applications (Fall 2019) and Categorical Data Analysis (Spring 2020) courses
-	Led team of 20 teaching assistants to deploy all logistical course details
-	Handled all course communications to a class of over 450 students
-	Built and maintained course websites
-	Taught weekly labs, held weekly office hours

#### Graduate Intern | Jun 2019 - Sep 2019 | New York City Department of Health
- Investigated associations between mental illness and socioeconomic/demographic risk factors using SAS (n = 10,000) 
- Created GIS heat map of depression prevalence across the five boroughs of New York City 
- [Presented](/pdf/Practicum_Poster_Alice_Tivarovsky.pdf) key findings to internal unit and broader bureau audience 

#### Sr Supply Chain Lead | Jan 2016 - May 2018 | Johnson & Johnson  
- Resolved supply chain disruptions with 46 chemical suppliers across Johnson & Johnson North America 
- Supported new product launches by building relationships with new suppliers and managing launch activities        

#### Manufacturing Engineer | Aug 2012 - Dec 2015 | Johnson & Johnson  
- Wrote FDA-ready technical reports and supported FDA audits leading to site “Best in Class” ranking 
- Designed user-friendly metrics and tracking and reporting tools for use by department management 
- Led team of 4 contractors, coaching investigative methods and overseeing all investigation activity
- Conducted investigations for quality issues leading to $1.5MM savings in defect-free product 
- Saved $164k annually by minimizing bulk waste, earning Six Sigma Green-Belt certification  

#### Chemical Engineer I | Oct 2009 - Aug 2012 | Johnson & Johnson  
- Achieved 40% reduction in cycle times by re-designing multi-phase processes for single-phase production 
- Re-designed and validated processes for 4 product formulas as part of Paraben elimination
