{
  "hash": "285579fbe68925eebe69643fed87d5e9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Visualizing Motor Vehicle Fatalities with ggplot2\"\nauthor: \"Alice Tivarovsky\"\ndate: '2020-07-17'\nslug: car-crashes\ntoc: true\ncategories:\n  - data visualization\n  - ggplot2\n  - injuries\n---\n\n*\"This is my favorite part about analytics: Taking boring flat data and bringing it to life through visualization.\" -- John Tukey*\n\n## Motivation\n\nLet's start with a morbid statistic: if you're younger than 30 and live in the United States, your most probable cause of death is a car crash.\n\nYou may have already known that. But here's a twist- your risk of dying in a car crash is heavily influenced by the city you live in. And although metropolitan density is an obvious factor, other variables including weather, state policy, type of car involved, and emergency response capabilities play a [huge role](https://www.iihs.org/topics/fatality-statistics/detail/state-by-state#fn1ref1).\n\nIn this post, we'll be using `ggplot2` - R's de-facto plotting package [^1] - to explore the relationship between city and motor vehicle fatalities in the US between 2010 and 2016.\n\n[^1]: There are people who would roast me for making that statement, given that R has an actual base graphics [package](https://www.rdocumentation.org/packages/graphics/versions/3.6.2) and from what I've seen, it works just fine. Data people on the internet sometimes [argue](https://flowingdata.com/2016/03/22/comparing-ggplot2-and-r-base-graphics/) against `ggplot2` since it seems the base graphics can get you similar results with less code. I have no position on the matter.\n\nWe'll be using data compiled from the [Big Cities Health Coalition](https://www.bigcitieshealth.org), a partnership organization comprised of public health leaders and thinkers from America's largest cities. I'd never heard of BCHC prior to this and I was genuinely impressed with the wealth of data and analyses published on their site.\n\n## Background\n\nIn the 1950s, the United States' mortality rate due to motor vehicle crashes was about [22 per 100,000](https://web.archive.org/web/20110921222129/http://www.saferoads.org/federal/2004/TrafficFatalities1899-2003.pdf) population. That proportion peaked at about 26 in the early 1970s and has since been steadily falling. Despite a somewhat alarming uptick in 2015, the proportion today hovers at [11 per 100,000](https://web.archive.org/web/20110921222129/http://www.saferoads.org/federal/2004/TrafficFatalities1899-2003.pdf).\n\nWhile that's undoubtedly huge progress, it still means that more than [35,000](https://www.cdc.gov/winnablebattles/report/motor.html) people die as a result of a motor vehicle crash every year. According to the [CDC](https://www.cdc.gov/vitalsigns/motor-vehicle-safety/index.html), about 1/3 of fatalities involve drunk drivers, another 1/3 involve drivers or passengers where proper restraints were not used (meaning seat belts, car seats, etc.), and another 1/3 involve drivers that were speeding.\n\nAnother somewhat sad statistic is that the reduction in motor vehicle fatalities in the U.S. has not kept pace with that of other high income countries. On average, high income countries reduced crash deaths by 56% between 2000 and 2013, compared with 31% in the U.S [CDC](https://www.cdc.gov/vitalsigns/motor-vehicle-safety/index.html). Today, the mortality rate in the U.S. (the 11 per 100,000 mentioned above) is by far the highest among high-income countries.\n\nInterestingly, states that are predominantly rural tend to have higher vehicle mortality rates. Mississippi (22.5 deaths/100,000 population), South Carolina (20.4 deaths/100,000 population), and Alabama (19.5 deaths/100,000 population) represent the highest rates, while New York (4.8 deaths/100,000 population), Massachusetts (5.2 deaths/100,000 population), and New Jersey (6.3 deaths/100,000 population) represent three of the lowest [IIHS](https://www.iihs.org/topics/fatality-statistics/detail/state-by-state). However, this divide is much less clear when we drill down to individual cities. Cary, NC, for instance, is one of the safest cities for drivers (1.3 fatal accidents per 100,000 population), while Detroit is one of the most dangerous (16.2 fatal accidents per 100,000 population) [Nerdwallet](https://www.nerdwallet.com/blog/insurance/dangerous-cities-car-drivers-2016/).\n\nLet's have a look at the data.\n\n## Data Preparation\n\n\n\n#### Data Source\n\nThese data were taken from the [data platform page](https://bchi.bigcitieshealth.org/indicators/1872/searches/34543) on the Big Cities Health Coalition [website](https://www.bigcitieshealth.org).\n\n#### Libraries\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(viridis)\nlibrary(plotly)\n```\n:::\n\n\n#### Data Import\n\nAccording to the website, this dataset was updated in March 2019. As loaded, the dataset contains 34,492 rows and 15 variables. We filter for only the motor vehicle fatality portion, which leaves us with 880 observations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrive_df = read.csv(file = \"./data/BCHI_dataset.csv\") %>% \n  janitor::clean_names() %>% \n  filter(indicator == \"Motor Vehicle Mortality Rate (Age-Adjusted; Per 100,000 people)\")\n```\n:::\n\n\n#### Data Tidy\n\nWe want to make sure that the variable types R gives us are correct, variables are appropriately named, and that everything we expected in the dataframe is indeed there. We also do a quick check to make sure the data are in wide format, wherein each observation is represented by a row and each variable measured for that observation is given in a column.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(drive_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t880 obs. of  15 variables:\n $ indicator_category        : chr  \"Injury/Violence\" \"Injury/Violence\" \"Injury/Violence\" \"Injury/Violence\" ...\n $ indicator                 : chr  \"Motor Vehicle Mortality Rate (Age-Adjusted; Per 100,000 people)\" \"Motor Vehicle Mortality Rate (Age-Adjusted; Per 100,000 people)\" \"Motor Vehicle Mortality Rate (Age-Adjusted; Per 100,000 people)\" \"Motor Vehicle Mortality Rate (Age-Adjusted; Per 100,000 people)\" ...\n $ year                      : int  2010 2010 2010 2010 2010 2010 2010 2010 2010 2010 ...\n $ sex                       : chr  \"Both\" \"Both\" \"Both\" \"Both\" ...\n $ race_ethnicity            : chr  \"All\" \"All\" \"All\" \"All\" ...\n $ value                     : num  2.6 3.9 4.3 5.5 5.6 5.8 6.1 6.5 6.7 6.7 ...\n $ place                     : chr  \"San Francisco, CA\" \"Seattle, WA\" \"Los Angeles, CA\" \"Oakland (Alameda County), CA\" ...\n $ bchc_requested_methodology: chr  \"Motor vehicle deaths per 100,000 population using 2010 US Census figures, age adjusted to the year 2000 standar\"| __truncated__ \"Motor vehicle deaths per 100,000 population using 2010 US Census figures, age adjusted to the year 2000 standar\"| __truncated__ \"Motor vehicle deaths per 100,000 population using 2010 US Census figures, age adjusted to the year 2000 standar\"| __truncated__ \"Motor vehicle deaths per 100,000 population using 2010 US Census figures, age adjusted to the year 2000 standar\"| __truncated__ ...\n $ source                    : chr  \"\" \"Washington State Department of Health, Center for Health Statistics, Death Certificate Data, 1990-2016, October 2017.\" \"Linked California DPH Death Statistical Master File for Los Angeles County residents, 2010-2012\" \"Alameda County vital statistics files\" ...\n $ methods                   : chr  \"\" \"\" \"Age-specific rates calculated using annual Los Angeles County population estimate created by LAC Internal Servi\"| __truncated__ \"Using 2010 mid-year population estimates\" ...\n $ notes                     : chr  \"Value is reported for a multi-year period, 2010-2012\" \"\" \"\" \"\" ...\n $ x90_confidence_level_low  : num  NA NA NA NA NA NA NA NA NA NA ...\n $ x90_confidence_level_high : num  NA NA NA NA NA NA NA NA NA NA ...\n $ x95_confidence_level_low  : num  2 2.5 NA 3.5 NA NA NA NA 5.1 5.4 ...\n $ x95_confidence_level_high : num  3.4 6 NA 8.3 NA NA NA NA 8.7 7.9 ...\n```\n\n\n:::\n:::\n\n\nIt looks like things are pretty clean. Most of the categorical variables, including race, sex, and city were read in as factors, while the mortality values and corresponding confidence intervals were read in using the double class. The only thing to fix is the `source`, `methods`, and `notes` variables, which should technically be strings since they don't contain any logical levels. I'm also going to change `year` to a categorical variable so R doesn't get confused trying to analyze it continuously.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrive_df = \n  drive_df %>% \n  mutate(year = as.factor(year), \n         source = as.character(source), \n         methods = as.character(methods),\n         notes = as.character(notes)\n  )\n```\n:::\n\n\n#### Variables Used\n\nThe variables we care about here are: - `year`: 2010 through 2016 - `sex`: Male, female, and the combined value under Both - `race_ethnicity`: American Indian/Alaska Native, Asian/PI, Black, Hispanic, Other, White, and combined valued (All) - `value`: the mortality value we'll be analyzing (i.e. our dependent variable); the details are given under `bchc_requested_methodology`, which explains that `value` is equal to motor vehicle deaths per 100,000 population using 2010 US Census figures, age adjusted to the 2000 census standard population. [^2] - `x90_confidence_level_low` and `x90_confidence_level_high`: 90% confidence interval around `value` - `x95_confidence_level_low` and `x95_confidence_level_high`: 95% confidence interval around `value`\n\n[^2]: Age adjustment is a method used in epidemiology when comparing rates of disease or mortality between populations with different age breakdowns. Roughly speaking, if the population of Austin TX, for instance, is much younger than the average U.S. population, it doesn't make sense to compare mortality rates directly. We know that older people die more frequently than younger people, so if we want an apples-to-apples comparison of two populations we have to use a weighting scheme. And that's all age standardization is - a weighting scheme that assigns more weight to certain age categories to \"equalize\" their weight to that of the reference population. In our example, older people in Austin would get weighted more than younger people.\n\n## Visualizing Motor Vehicle Fatalities\n\n`ggplot2` works by layering graphical elements on top of one another. These layers are referred to as \"geoms\" and they include things like axes, grid lines, color schemes points representing your data, trend-lines connecting your data, shaded regions representing confidence intervals, and plot labels, titles, and legends. Creating a final graph requires you to define each element individually and \"add\" it to the `ggplot()` call.\n\nThe best way to explain `ggplot2` is, of course, to demonstrate it. Let's first just apply the function to our dataframe `drive_df` to see what happens.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrive_df %>% \n  ggplot()\n```\n\n::: {.cell-output-display}\n![](car-crashes_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\nWe get this lovely gray square. Who doesn't love gray squares?\n\nThis may seem silly but the point is to demonstrate that `ggplot2` needs you to state what you want.\n\nThe first thing we need to do is tell `ggplot2` what our dependent and independent variables are. We're interested in motor vehicle mortality year over year, so let's try the following:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrive_df %>% \n  ggplot(x = year, y = value)\n```\n\n::: {.cell-output-display}\n![](car-crashes_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\nWait what?\n\nAnd this is one of the first lessons of `ggplot2`. In order to control how things look within a geom, you have to set what are known as **aesthetics**.\n\n### Aesthetics\n\nAesthetics set within the ggplot function itself (i.e. before geoms are defined) are global aesthetics that apply to the entire plot. Aesthetics set within a geom apply only to that geom. Therefore, when we define axes, we want to set them globally within a `ggplot(aes()` call:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrive_df %>% \n  ggplot(aes(x = year, y = value))\n```\n\n::: {.cell-output-display}\n![](car-crashes_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nAh, now we're getting somewhere.\n\nLet's attempt to create a plot of motor vehicle mortality as a function of year. We know that we have data from 2010 through 2016 and that the data are collected (or compiled) annually. In order to get some points for each year, we'll need to \"add\" a point geom to `ggplot2`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrive_df %>% \n  ggplot(aes(x = year, y = value)) + \n  geom_point()\n```\n\n::: {.cell-output-display}\n![](car-crashes_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nClearly this is a pretty bad plot and if you ever see something like this published, please assume that the author doesn't know much about plots. For one thing, using a scatterplot doesn't make sense because the year variable was measured categorically rather than continuously. BUT... this does show us something important in the data: **outliers**. On the left, we have points hovering at 70-75 deaths per 100,000. Recall that in the 1970s, when motor vehicle deaths peaked, the average values reached into the mid-20s. So clearly, 75 is astronomical. Let's take a detour and investigate this a bit more. I'm going to go back to the dataframe and sort in order of decreasing `value`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrive_df %>% \n  arrange(desc(value)) %>% \n  head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  indicator_category\n1    Injury/Violence\n2    Injury/Violence\n3    Injury/Violence\n4    Injury/Violence\n5    Injury/Violence\n6    Injury/Violence\n                                                        indicator year  sex\n1 Motor Vehicle Mortality Rate (Age-Adjusted; Per 100,000 people) 2011 Both\n2 Motor Vehicle Mortality Rate (Age-Adjusted; Per 100,000 people) 2012 Both\n3 Motor Vehicle Mortality Rate (Age-Adjusted; Per 100,000 people) 2010 Both\n4 Motor Vehicle Mortality Rate (Age-Adjusted; Per 100,000 people) 2012 Both\n5 Motor Vehicle Mortality Rate (Age-Adjusted; Per 100,000 people) 2016 Both\n6 Motor Vehicle Mortality Rate (Age-Adjusted; Per 100,000 people) 2012 Both\n                 race_ethnicity value           place\n1                         Other  74.4      Denver, CO\n2                         Other  74.4      Denver, CO\n3 American Indian/Alaska Native  70.5 Minneapolis, MN\n4 American Indian/Alaska Native  39.4 Minneapolis, MN\n5                      Hispanic  35.6 Minneapolis, MN\n6                      Hispanic  34.1 Minneapolis, MN\n                                                                                                                                                                                                                                                                            bchc_requested_methodology\n1 Motor vehicle deaths per 100,000 population using 2010 US Census figures, age adjusted to the year 2000 standard population. ICD-10 Codes: V02-V04, V09.0, V09.2, V12-V14, V19.0-V19.2, V19.4-V19.6, V20-V79, V80.3-V80.5, V81.0-V81.1, V82.0-V82.1, V83-V86, V87.0-V87.8, V88.0-V88.8, V89.0, V89.2\n2 Motor vehicle deaths per 100,000 population using 2010 US Census figures, age adjusted to the year 2000 standard population. ICD-10 Codes: V02-V04, V09.0, V09.2, V12-V14, V19.0-V19.2, V19.4-V19.6, V20-V79, V80.3-V80.5, V81.0-V81.1, V82.0-V82.1, V83-V86, V87.0-V87.8, V88.0-V88.8, V89.0, V89.2\n3 Motor vehicle deaths per 100,000 population using 2010 US Census figures, age adjusted to the year 2000 standard population. ICD-10 Codes: V02-V04, V09.0, V09.2, V12-V14, V19.0-V19.2, V19.4-V19.6, V20-V79, V80.3-V80.5, V81.0-V81.1, V82.0-V82.1, V83-V86, V87.0-V87.8, V88.0-V88.8, V89.0, V89.2\n4 Motor vehicle deaths per 100,000 population using 2010 US Census figures, age adjusted to the year 2000 standard population. ICD-10 Codes: V02-V04, V09.0, V09.2, V12-V14, V19.0-V19.2, V19.4-V19.6, V20-V79, V80.3-V80.5, V81.0-V81.1, V82.0-V82.1, V83-V86, V87.0-V87.8, V88.0-V88.8, V89.0, V89.2\n5 Motor vehicle deaths per 100,000 population using 2010 US Census figures, age adjusted to the year 2000 standard population. ICD-10 Codes: V02-V04, V09.0, V09.2, V12-V14, V19.0-V19.2, V19.4-V19.6, V20-V79, V80.3-V80.5, V81.0-V81.1, V82.0-V82.1, V83-V86, V87.0-V87.8, V88.0-V88.8, V89.0, V89.2\n6 Motor vehicle deaths per 100,000 population using 2010 US Census figures, age adjusted to the year 2000 standard population. ICD-10 Codes: V02-V04, V09.0, V09.2, V12-V14, V19.0-V19.2, V19.4-V19.6, V20-V79, V80.3-V80.5, V81.0-V81.1, V82.0-V82.1, V83-V86, V87.0-V87.8, V88.0-V88.8, V89.0, V89.2\n                             source\n1 Colorado Vital Records Death Data\n2 Colorado Vital Records Death Data\n3        Minnesota Vital Statistics\n4        Minnesota Vital Statistics\n5        Minnesota Vital Statistics\n6        Minnesota Vital Statistics\n                                                                                                                        methods\n1                                                            2011-2013 years are the most recently available data at this time.\n2                                                            2011-2013 years are the most recently available data at this time.\n3 Rates per 100,000 calculated using the Minneapolis 2010 Census population; age-adjusted using the 2000 US standard population\n4 Rates per 100,000 calculated using the Minneapolis 2010 Census population; age-adjusted using the 2000 US standard population\n5                                                                                                                              \n6 Rates per 100,000 calculated using the Minneapolis 2010 Census population; age-adjusted using the 2000 US standard population\n  notes x90_confidence_level_low x90_confidence_level_high\n1                             NA                        NA\n2                             NA                        NA\n3                             NA                        NA\n4                             NA                        NA\n5                             NA                        NA\n6                             NA                        NA\n  x95_confidence_level_low x95_confidence_level_high\n1                       NA                        NA\n2                       NA                        NA\n3                       NA                        NA\n4                       NA                        NA\n5                       NA                        NA\n6                       NA                        NA\n```\n\n\n:::\n:::\n\n\nThe top three outliers belong to 2011 Denver, CO (74.4 deaths), 2012 Denver, CO (also 74.4 deaths), and 2010 Minneapolis, MN (70.5 deaths). What's important is that these are race-stratified. While all three represent total values for both males and females, the Denver numbers represent data for race labeled \"Other\" and the Minneapolis number belongs to the American Indian/Alaska Native population. If we wanted to dig around, we could perhaps find the original Denver and Minneapolis data and double check these numbers. They might be correct or they might be attributed to typos.\n\nIn this case, we're not interested in racial distribution for the moment, so we're going to restrict our dataset to the collapsed values, meaning those representing the averages of both sexes and all races. Then we'll re-attempt the pseudo-scatterplot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrive_df %>% \n  filter(sex == \"Both\", race_ethnicity == \"All\") %>% \n  ggplot(aes(x = year, y = value)) + \n  geom_point()\n```\n\n::: {.cell-output-display}\n![](car-crashes_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nOk, that's a little better, but it still doesn't tell us anything interesting. Each year has many data points representing an individual city and on this plot, it's impossible to tell which city corresponds to which point. We'll come back to this question in a moment, but for now, let's try to extract something useful from the plot. Let's try to answer the question: **on average, did motor vehicle fatalities in the U.S. increase, decrease, or remain stable between 2010 and 2016?** To visualize the answer, we'll need a plot that can show us the center value of each year, and maybe some indication of the distribution within that year. Enter the boxplot.\n\n### Boxplots\n\nHere's a wonderful TDS [post](https://towardsdatascience.com/understanding-boxplots-5e2df7bcbd51) on boxplots. Let's see what happens when we use one here.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrive_df %>% \n  filter(sex == \"Both\", race_ethnicity == \"All\") %>% \n  ggplot(aes(x = year, y = value)) + \n    geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](car-crashes_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nImmediately we gleaned a useful nugget of information: there was an alarming spike in the data. Things were chugging along and then something happened in 2015. If you do a news search on this topic, you'll see that public health and safety folks [noticed](https://www.npr.org/sections/thetwo-way/2016/02/18/467230965/2015-traffic-fatalities-rose-by-largest-percent-in-50-years-safety-group-says) this, too. It looks like fuel prices and job growth were potential culprits, but either way, this is clearly a very useful insight.\n\nLet's spice this plot up a bit. Let's say we want to compare men and women in the same time frame. We will need to specify a color code within the aesthetic for `geom_boxplot` and we'll also need to filter out the \"Both\" values for sex, since we just want male vs female.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrive_df %>% \n  filter(race_ethnicity == \"All\", !sex == \"Both\") %>% \n  ggplot(aes(x = year, y = value, fill = sex)) + \n    geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](car-crashes_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nThere's an obvious disparity in mortality between males and females. Most years, male fatality averages are more than double that of females, and some years (2015, for instance) it's more like triple. The female boxplot for 2016 also looks suspiciously narrow. It's worth investigating but for now let's move on.\n\nLet's use some nicer colors. For two-tone plots, I like to just manually choose the colors (there are a million color tools online, but [this one](https://coolors.co) is my favorite). For three or more colors, I normally use a package like [`RColorBrewer`](https://cran.r-project.org/web/packages/RColorBrewer/RColorBrewer.pdf) (built-in) or the extra-fancy [`viridis`](https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html) package, which you'd need to install. I'm also going to get rid of the gray background using a theme and change the opacity of the fill color using an `alpha` statement (the latter is just personal preference). Finally, I'll capitalize the axis labels, and add a title and caption.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrive_df %>% \n  filter(race_ethnicity == \"All\", !sex == \"Both\") %>% \n  ggplot(aes(x = year, y = value, fill = sex)) + \n    #change outline color to gray\n    geom_boxplot(alpha = 0.7) +\n    scale_fill_manual(values=c(\"#996699\", \"#99CC99\")) + \n    theme_bw() +\n    labs(\n      title = \"Motor Vehicle Fatality Rate 2010-2016 by Sex\",\n      x = \"Year\",\n      y = \"Fatality (death/100,000 population)\",\n      caption = \"Data source: Big Cities Health Initiative\"\n    )\n```\n\n::: {.cell-output-display}\n![](car-crashes_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nGreat, we wound up with a nice-looking boxplot with some useful information.\n\n### Violin Plots\n\nNow let's take a look at a cousin of the boxplot: the violin plot. All you really need to know to understand how it works is shown in this figure, taken from another [TDS post](https://towardsdatascience.com/violin-plots-explained-fb1d115e023d).\n\n![](/image/violin.png){width=\"50%\"}\n\nThere was a time a few years back when everyone thought violin plots were the best thing since sliced bagels. The trend seems to have somewhat faded but I think they're nice so let's make one.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrive_df %>% \n  filter(sex == \"Both\", race_ethnicity == \"All\") %>%\n  ggplot(aes(x = year, y = value)) + \n    geom_violin()\n```\n\n::: {.cell-output-display}\n![](car-crashes_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nIs it just me or do these look like a Dr. Seuss version of stick-figures?\n\nAnyway, these aren't very \"violin-y\" but the point is that higher frequencies of values lead to wider parts of the plots and vice-versa. If we want to see a more violin shape, we can combine some of the years to get more data points per 'violin\". Let's do that here:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrive_df %>% \n  filter(sex == \"Both\", race_ethnicity == \"All\") %>%\n  mutate(year_group = if_else(year %in% c(2010, 2011, 2012), \"2010-2012\", \"2013-2016\")) %>% \n  ggplot(aes(x = year_group, y = value)) + \n    geom_violin()\n```\n\n::: {.cell-output-display}\n![](car-crashes_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nMuch more violin-like! Clearly, the 2010-2012 group had most of its data points in the 6-6.5 range, while 2013-2016 was a bit more spread out across its range of values and its median is a bit higher (probably driven by that alarming 2015 number).\n\nWhat if we split out males vs females like we did in our boxplots?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nviolin = \ndrive_df %>% \n  filter(!sex == \"Both\", race_ethnicity == \"All\") %>%\n  mutate(year_group = if_else(year %in% c(2010, 2011, 2012), \"2010-2012\", \"2013-2016\")) %>% \n  ggplot(aes(x = year_group, y = value, fill = sex)) + \n    geom_violin(alpha = 0.7)\n\nviolin\n```\n\n::: {.cell-output-display}\n![](car-crashes_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nThe gender difference we saw in the boxplots is even more detailed here.\n\nLet's clean this up a bit and then we're going to do something **really** exciting.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nviolin_1 = \n  violin +\n  scale_fill_manual(values=c(\"#996699\", \"#99CC99\")) + \n  theme_bw() +\n  labs(\n      title = \"Motor Vehicle Fatality Rates, Early vs Mid 2000s by Sex\",\n      x = \"Year\",\n      y = \"Fatality (death/100,000 population)\",\n      caption = \"Data source: Big Cities Health Initiative\"\n    )\n\nviolin_1\n```\n\n::: {.cell-output-display}\n![](car-crashes_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nAll right, let's get extra fancy. We're going to use a function within `ggplot2` called `stat_summary` to give us some extra detail.\n\n#### `stat_summary()`\n\n`stat_summary` does just what it sounds like - it summarizes stats. We've been using stats within our geoms this whole time, we just didn't know about it because `ggplot2` does it in the background. For instance, the boxplot geom calculates the median, 25th, and 75th percentile stats.\n\nHere, we'll add dots to indicate the median in each violin. The `position_dodge` function moves the dots inside the violins, as opposed to positioning them directly on the gridline.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nviolin_1 +\n  stat_summary(fun = median, geom=\"point\", position = position_dodge(width = 0.9))\n```\n\n::: {.cell-output-display}\n![](car-crashes_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nviolin_1 +\n  stat_summary(fun.data = mean_sdl, geom = \"pointrange\", position = position_dodge(width = 0.9))\n```\n\n::: {.cell-output-display}\n![](car-crashes_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nThere are lots of other stats you can layer on. You can even embed little boxplots within the violin plots. [This page](http://www.sthda.com/english/wiki/ggplot2-violin-plot-quick-start-guide-r-software-and-data-visualization) gives a great summary, but for our purposes we're going to end our mini-tour of violin plots here and move on.\n\n### Points and Lines\n\nNow let's come back to our initial question of how motor vehicle fatalities differ across cities in the U.S. Recall that we started with the scatterplot below:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrive_df %>% \n  filter(sex == \"Both\", race_ethnicity == \"All\") %>% \n  ggplot(aes(x = year, y = value)) + \n  geom_point()\n```\n\n::: {.cell-output-display}\n![](car-crashes_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nEvery dot represents a city and every city has a value for every year of measurement, so of course we want to know which dot belongs to which city.\n\nLet's start with some basic color-coding.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrive_df %>% \n  filter(sex == \"Both\", race_ethnicity == \"All\") %>% \n  ggplot(aes(x = year, y = value)) + \n  geom_point(aes(color = place))\n```\n\n::: {.cell-output-display}\n![](car-crashes_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\nYikes. It's basically impossible to distinguish any of these colors from one another, or to follow the trajectory of any city year to year. We need lines rather than dots. We also need `ggplot2` to know that each city should be treated as a grouping (this latter point is not super intuitive to me, but just know that it doesn't work otherwise).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrive_df %>% \n  filter(sex == \"Both\", race_ethnicity == \"All\") %>% \n  ggplot(aes(x = year, y = value, group = place)) + \n  geom_line()  \n```\n\n::: {.cell-output-display}\n![](car-crashes_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\nDoes this bring back fond [Etch A Sketch](https://etchasketch.com) memories?\n\nWhat we've created here is called a **spaghetti plot** for reasons that should be obvious. Clearly we need colors though. Let's drop a color aesthetic into our line geom.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspaghetti_plot = \ndrive_df %>% \n  filter(sex == \"Both\", race_ethnicity == \"All\") %>% \n  ggplot(aes(x = year, y = value, group = place)) + \n  geom_line(aes(color = place)) \n\nspaghetti_plot\n```\n\n::: {.cell-output-display}\n![](car-crashes_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\nYikes. Too many similar colors. Also, too much legend.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspaghetti_plot_1 = \n  spaghetti_plot +\n  scale_color_viridis(discrete = TRUE) + \n  theme_bw() + \n  theme(legend.position = \"bottom\", legend.title = element_text(size = 8),\n  legend.text = element_text(size = 6) \n  ) +\n  labs(\n      title = \"Motor Vehicle Fatality Rates by City\",\n      x = \"Year\",\n      y = \"Fatality (death/100,000 population)\",\n      caption = \"Data source: Big Cities Health Initiative\"\n    )\n\nspaghetti_plot_1\n```\n\n::: {.cell-output-display}\n![](car-crashes_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\nThat's a lot better, but there's still no way anyone would be able to distinguish Houston from Indianapolis, or even be able to infer which city has the highest crash fatality burden versus lowest. And this is where interactivity comes in handy.\n\nA word of warning, it's easy to over-do interactivity and go nuts with things like `plotly` because it's fun and flashy. Don't do it. If it doesn't add value to visualizing patterns in the data, it doesn't have any place on your plot.\n\n### `ggplotly`\n\nIn this case, we definitely want some interactivity to help us understand the data. We're going to use [`ggplotly`](https://www.rdocumentation.org/packages/plotly/versions/4.9.2.1/topics/ggplotly), a convenient marriage of `plotly` and `ggplot2`. You can hover on a line to see which city it represents, or double any city in the legend to isolate it on the plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspaghetti_plot_1 %>% \n  ggplotly()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-b6de61c1b779ebe8dc2a\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-b6de61c1b779ebe8dc2a\">{\"x\":{\"data\":[{\"x\":[1,3,4,5,6],\"y\":[null,5,4.7000000000000002,4.2999999999999998,3.7999999999999998],\"text\":[\"year: 2010<br />value:   NA<br />place: Boston, MA<br />place: Boston, MA\",\"year: 2012<br />value:  5.0<br />place: Boston, MA<br />place: Boston, MA\",\"year: 2013<br />value:  4.7<br />place: Boston, MA<br />place: Boston, MA\",\"year: 2014<br />value:  4.3<br />place: Boston, MA<br />place: Boston, MA\",\"year: 2015<br />value:  3.8<br />place: Boston, MA<br />place: Boston, MA\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(68,1,84,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Boston, MA\",\"legendgroup\":\"Boston, MA\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1,2,3,4],\"y\":[5.7999999999999998,5.7000000000000002,6.5,6.2999999999999998],\"text\":[\"year: 2010<br />value:  5.8<br />place: Chicago, Il<br />place: Chicago, Il\",\"year: 2011<br />value:  5.7<br />place: Chicago, Il<br />place: Chicago, Il\",\"year: 2012<br />value:  6.5<br />place: Chicago, Il<br />place: Chicago, Il\",\"year: 2013<br />value:  6.3<br />place: Chicago, Il<br />place: Chicago, Il\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(71,16,99,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Chicago, Il\",\"legendgroup\":\"Chicago, Il\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[3,4,5],\"y\":[7.2999999999999998,7.0999999999999996,6.2999999999999998],\"text\":[\"year: 2012<br />value:  7.3<br />place: Cleveland, OH<br />place: Cleveland, OH\",\"year: 2013<br />value:  7.1<br />place: Cleveland, OH<br />place: Cleveland, OH\",\"year: 2014<br />value:  6.3<br />place: Cleveland, OH<br />place: Cleveland, OH\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(72,29,111,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Cleveland, OH\",\"legendgroup\":\"Cleveland, OH\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1,2,3,4,6,7],\"y\":[9.4000000000000004,10.699999999999999,10.5,8.3000000000000007,12.1,12.800000000000001],\"text\":[\"year: 2010<br />value:  9.4<br />place: Columbus, OH<br />place: Columbus, OH\",\"year: 2011<br />value: 10.7<br />place: Columbus, OH<br />place: Columbus, OH\",\"year: 2012<br />value: 10.5<br />place: Columbus, OH<br />place: Columbus, OH\",\"year: 2013<br />value:  8.3<br />place: Columbus, OH<br />place: Columbus, OH\",\"year: 2015<br />value: 12.1<br />place: Columbus, OH<br />place: Columbus, OH\",\"year: 2016<br />value: 12.8<br />place: Columbus, OH<br />place: Columbus, OH\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(72,41,122,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Columbus, OH\",\"legendgroup\":\"Columbus, OH\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1,2,3,4,5,6,7],\"y\":[8.5,7.2000000000000002,6.5,8.4000000000000004,7.7000000000000002,10.699999999999999,13.5],\"text\":[\"year: 2010<br />value:  8.5<br />place: Denver, CO<br />place: Denver, CO\",\"year: 2011<br />value:  7.2<br />place: Denver, CO<br />place: Denver, CO\",\"year: 2012<br />value:  6.5<br />place: Denver, CO<br />place: Denver, CO\",\"year: 2013<br />value:  8.4<br />place: Denver, CO<br />place: Denver, CO\",\"year: 2014<br />value:  7.7<br />place: Denver, CO<br />place: Denver, CO\",\"year: 2015<br />value: 10.7<br />place: Denver, CO<br />place: Denver, CO\",\"year: 2016<br />value: 13.5<br />place: Denver, CO<br />place: Denver, CO\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(69,53,129,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Denver, CO\",\"legendgroup\":\"Denver, CO\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[2,3,4,5],\"y\":[9,12.9,12.9,13.199999999999999],\"text\":[\"year: 2011<br />value:  9.0<br />place: Detroit, MI<br />place: Detroit, MI\",\"year: 2012<br />value: 12.9<br />place: Detroit, MI<br />place: Detroit, MI\",\"year: 2013<br />value: 12.9<br />place: Detroit, MI<br />place: Detroit, MI\",\"year: 2014<br />value: 13.2<br />place: Detroit, MI<br />place: Detroit, MI\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(66,65,134,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Detroit, MI\",\"legendgroup\":\"Detroit, MI\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1,2,3,4,5],\"y\":[9.3000000000000007,10.9,9.9000000000000004,11.6,9.8000000000000007],\"text\":[\"year: 2010<br />value:  9.3<br />place: Fort Worth (Tarrant County), TX<br />place: Fort Worth (Tarrant County), TX\",\"year: 2011<br />value: 10.9<br />place: Fort Worth (Tarrant County), TX<br />place: Fort Worth (Tarrant County), TX\",\"year: 2012<br />value:  9.9<br />place: Fort Worth (Tarrant County), TX<br />place: Fort Worth (Tarrant County), TX\",\"year: 2013<br />value: 11.6<br />place: Fort Worth (Tarrant County), TX<br />place: Fort Worth (Tarrant County), TX\",\"year: 2014<br />value:  9.8<br />place: Fort Worth (Tarrant County), TX<br />place: Fort Worth (Tarrant County), TX\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(61,77,138,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Fort Worth (Tarrant County), TX\",\"legendgroup\":\"Fort Worth (Tarrant County), TX\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1,2,3],\"y\":[10.1,9.8000000000000007,9.6999999999999993],\"text\":[\"year: 2010<br />value: 10.1<br />place: Houston, TX<br />place: Houston, TX\",\"year: 2011<br />value:  9.8<br />place: Houston, TX<br />place: Houston, TX\",\"year: 2012<br />value:  9.7<br />place: Houston, TX<br />place: Houston, TX\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(56,87,140,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Houston, TX\",\"legendgroup\":\"Houston, TX\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1,2,3,4,5,7],\"y\":[6.7000000000000002,7.2999999999999998,5.9000000000000004,6.5,5.4000000000000004,8.9000000000000004],\"text\":[\"year: 2010<br />value:  6.7<br />place: Indianapolis (Marion County), IN<br />place: Indianapolis (Marion County), IN\",\"year: 2011<br />value:  7.3<br />place: Indianapolis (Marion County), IN<br />place: Indianapolis (Marion County), IN\",\"year: 2012<br />value:  5.9<br />place: Indianapolis (Marion County), IN<br />place: Indianapolis (Marion County), IN\",\"year: 2013<br />value:  6.5<br />place: Indianapolis (Marion County), IN<br />place: Indianapolis (Marion County), IN\",\"year: 2014<br />value:  5.4<br />place: Indianapolis (Marion County), IN<br />place: Indianapolis (Marion County), IN\",\"year: 2016<br />value:  8.9<br />place: Indianapolis (Marion County), IN<br />place: Indianapolis (Marion County), IN\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(52,97,141,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Indianapolis (Marion County), IN\",\"legendgroup\":\"Indianapolis (Marion County), IN\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1,2,3,4,5,6,7],\"y\":[12.6,9.8000000000000007,10.699999999999999,9,9.4000000000000004,10.800000000000001,11.5],\"text\":[\"year: 2010<br />value: 12.6<br />place: Kansas City, MO<br />place: Kansas City, MO\",\"year: 2011<br />value:  9.8<br />place: Kansas City, MO<br />place: Kansas City, MO\",\"year: 2012<br />value: 10.7<br />place: Kansas City, MO<br />place: Kansas City, MO\",\"year: 2013<br />value:  9.0<br />place: Kansas City, MO<br />place: Kansas City, MO\",\"year: 2014<br />value:  9.4<br />place: Kansas City, MO<br />place: Kansas City, MO\",\"year: 2015<br />value: 10.8<br />place: Kansas City, MO<br />place: Kansas City, MO\",\"year: 2016<br />value: 11.5<br />place: Kansas City, MO<br />place: Kansas City, MO\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(47,107,142,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Kansas City, MO\",\"legendgroup\":\"Kansas City, MO\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1,2,3,4,5,6],\"y\":[8.6999999999999993,7.7999999999999998,8.8000000000000007,9.0999999999999996,8.8000000000000007,10.6],\"text\":[\"year: 2010<br />value:  8.7<br />place: Las Vegas (Clark County), NV<br />place: Las Vegas (Clark County), NV\",\"year: 2011<br />value:  7.8<br />place: Las Vegas (Clark County), NV<br />place: Las Vegas (Clark County), NV\",\"year: 2012<br />value:  8.8<br />place: Las Vegas (Clark County), NV<br />place: Las Vegas (Clark County), NV\",\"year: 2013<br />value:  9.1<br />place: Las Vegas (Clark County), NV<br />place: Las Vegas (Clark County), NV\",\"year: 2014<br />value:  8.8<br />place: Las Vegas (Clark County), NV<br />place: Las Vegas (Clark County), NV\",\"year: 2015<br />value: 10.6<br />place: Las Vegas (Clark County), NV<br />place: Las Vegas (Clark County), NV\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(43,116,142,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Las Vegas (Clark County), NV\",\"legendgroup\":\"Las Vegas (Clark County), NV\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[2,3,4,5],\"y\":[4.5,6.0999999999999996,3.8999999999999999,4.4000000000000004],\"text\":[\"year: 2011<br />value:  4.5<br />place: Long Beach, CA<br />place: Long Beach, CA\",\"year: 2012<br />value:  6.1<br />place: Long Beach, CA<br />place: Long Beach, CA\",\"year: 2013<br />value:  3.9<br />place: Long Beach, CA<br />place: Long Beach, CA\",\"year: 2014<br />value:  4.4<br />place: Long Beach, CA<br />place: Long Beach, CA\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(39,126,142,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Long Beach, CA\",\"legendgroup\":\"Long Beach, CA\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1,2,3],\"y\":[4.2999999999999998,3.7000000000000002,4.0999999999999996],\"text\":[\"year: 2010<br />value:  4.3<br />place: Los Angeles, CA<br />place: Los Angeles, CA\",\"year: 2011<br />value:  3.7<br />place: Los Angeles, CA<br />place: Los Angeles, CA\",\"year: 2012<br />value:  4.1<br />place: Los Angeles, CA<br />place: Los Angeles, CA\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(36,135,142,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Los Angeles, CA\",\"legendgroup\":\"Los Angeles, CA\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[2,3,4,5],\"y\":[10.300000000000001,9.9000000000000004,8.8000000000000007,10.1],\"text\":[\"year: 2011<br />value: 10.3<br />place: Miami (Miami-Dade County), FL<br />place: Miami (Miami-Dade County), FL\",\"year: 2012<br />value:  9.9<br />place: Miami (Miami-Dade County), FL<br />place: Miami (Miami-Dade County), FL\",\"year: 2013<br />value:  8.8<br />place: Miami (Miami-Dade County), FL<br />place: Miami (Miami-Dade County), FL\",\"year: 2014<br />value: 10.1<br />place: Miami (Miami-Dade County), FL<br />place: Miami (Miami-Dade County), FL\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(33,144,140,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Miami (Miami-Dade County), FL\",\"legendgroup\":\"Miami (Miami-Dade County), FL\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1,2,3,4,5,6,7],\"y\":[6.5,3.2999999999999998,4.5999999999999996,6.5999999999999996,2.7999999999999998,3.2999999999999998,6.5999999999999996],\"text\":[\"year: 2010<br />value:  6.5<br />place: Minneapolis, MN<br />place: Minneapolis, MN\",\"year: 2011<br />value:  3.3<br />place: Minneapolis, MN<br />place: Minneapolis, MN\",\"year: 2012<br />value:  4.6<br />place: Minneapolis, MN<br />place: Minneapolis, MN\",\"year: 2013<br />value:  6.6<br />place: Minneapolis, MN<br />place: Minneapolis, MN\",\"year: 2014<br />value:  2.8<br />place: Minneapolis, MN<br />place: Minneapolis, MN\",\"year: 2015<br />value:  3.3<br />place: Minneapolis, MN<br />place: Minneapolis, MN\",\"year: 2016<br />value:  6.6<br />place: Minneapolis, MN<br />place: Minneapolis, MN\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(31,153,138,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Minneapolis, MN\",\"legendgroup\":\"Minneapolis, MN\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[2,4,5,6],\"y\":[3.3999999999999999,3.6000000000000001,3.1000000000000001,2.8999999999999999],\"text\":[\"year: 2011<br />value:  3.4<br />place: New York City, NY<br />place: New York City, NY\",\"year: 2013<br />value:  3.6<br />place: New York City, NY<br />place: New York City, NY\",\"year: 2014<br />value:  3.1<br />place: New York City, NY<br />place: New York City, NY\",\"year: 2015<br />value:  2.9<br />place: New York City, NY<br />place: New York City, NY\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(31,162,135,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"New York City, NY\",\"legendgroup\":\"New York City, NY\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1,2,3,4,5,6,7],\"y\":[5.5,6.7000000000000002,12.9,7.7000000000000002,5.9000000000000004,10.300000000000001,8.5999999999999996],\"text\":[\"year: 2010<br />value:  5.5<br />place: Oakland (Alameda County), CA<br />place: Oakland (Alameda County), CA\",\"year: 2011<br />value:  6.7<br />place: Oakland (Alameda County), CA<br />place: Oakland (Alameda County), CA\",\"year: 2012<br />value: 12.9<br />place: Oakland (Alameda County), CA<br />place: Oakland (Alameda County), CA\",\"year: 2013<br />value:  7.7<br />place: Oakland (Alameda County), CA<br />place: Oakland (Alameda County), CA\",\"year: 2014<br />value:  5.9<br />place: Oakland (Alameda County), CA<br />place: Oakland (Alameda County), CA\",\"year: 2015<br />value: 10.3<br />place: Oakland (Alameda County), CA<br />place: Oakland (Alameda County), CA\",\"year: 2016<br />value:  8.6<br />place: Oakland (Alameda County), CA<br />place: Oakland (Alameda County), CA\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(37,172,130,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Oakland (Alameda County), CA\",\"legendgroup\":\"Oakland (Alameda County), CA\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1,2,3,4,5,7],\"y\":[6.7000000000000002,6.7999999999999998,6.7999999999999998,7,6.7000000000000002,7.2000000000000002],\"text\":[\"year: 2010<br />value:  6.7<br />place: Philadelphia, PA<br />place: Philadelphia, PA\",\"year: 2011<br />value:  6.8<br />place: Philadelphia, PA<br />place: Philadelphia, PA\",\"year: 2012<br />value:  6.8<br />place: Philadelphia, PA<br />place: Philadelphia, PA\",\"year: 2013<br />value:  7.0<br />place: Philadelphia, PA<br />place: Philadelphia, PA\",\"year: 2014<br />value:  6.7<br />place: Philadelphia, PA<br />place: Philadelphia, PA\",\"year: 2016<br />value:  7.2<br />place: Philadelphia, PA<br />place: Philadelphia, PA\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(49,181,123,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Philadelphia, PA\",\"legendgroup\":\"Philadelphia, PA\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[3,5],\"y\":[8.6999999999999993,10],\"text\":[\"year: 2012<br />value:  8.7<br />place: Phoenix, AZ<br />place: Phoenix, AZ\",\"year: 2014<br />value: 10.0<br />place: Phoenix, AZ<br />place: Phoenix, AZ\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(64,188,114,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Phoenix, AZ\",\"legendgroup\":\"Phoenix, AZ\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[2,3,4,5,6,7],\"y\":[4.5,6,7.5999999999999996,5.7000000000000002,6.2000000000000002,null],\"text\":[\"year: 2011<br />value:  4.5<br />place: Portland (Multnomah County), OR<br />place: Portland (Multnomah County), OR\",\"year: 2012<br />value:  6.0<br />place: Portland (Multnomah County), OR<br />place: Portland (Multnomah County), OR\",\"year: 2013<br />value:  7.6<br />place: Portland (Multnomah County), OR<br />place: Portland (Multnomah County), OR\",\"year: 2014<br />value:  5.7<br />place: Portland (Multnomah County), OR<br />place: Portland (Multnomah County), OR\",\"year: 2015<br />value:  6.2<br />place: Portland (Multnomah County), OR<br />place: Portland (Multnomah County), OR\",\"year: 2016<br />value:   NA<br />place: Portland (Multnomah County), OR<br />place: Portland (Multnomah County), OR\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(83,197,105,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Portland (Multnomah County), OR\",\"legendgroup\":\"Portland (Multnomah County), OR\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1,2,3,4,5,6],\"y\":[8.9000000000000004,6.4000000000000004,7.7999999999999998,7.5999999999999996,10.6,12],\"text\":[\"year: 2010<br />value:  8.9<br />place: San Antonio, TX<br />place: San Antonio, TX\",\"year: 2011<br />value:  6.4<br />place: San Antonio, TX<br />place: San Antonio, TX\",\"year: 2012<br />value:  7.8<br />place: San Antonio, TX<br />place: San Antonio, TX\",\"year: 2013<br />value:  7.6<br />place: San Antonio, TX<br />place: San Antonio, TX\",\"year: 2014<br />value: 10.6<br />place: San Antonio, TX<br />place: San Antonio, TX\",\"year: 2015<br />value: 12.0<br />place: San Antonio, TX<br />place: San Antonio, TX\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(103,204,92,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"San Antonio, TX\",\"legendgroup\":\"San Antonio, TX\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1,2,3,4,5,6,7],\"y\":[6.0999999999999996,6.0999999999999996,6.7000000000000002,6.0999999999999996,7,7.0999999999999996,7.2999999999999998],\"text\":[\"year: 2010<br />value:  6.1<br />place: San Diego County, CA<br />place: San Diego County, CA\",\"year: 2011<br />value:  6.1<br />place: San Diego County, CA<br />place: San Diego County, CA\",\"year: 2012<br />value:  6.7<br />place: San Diego County, CA<br />place: San Diego County, CA\",\"year: 2013<br />value:  6.1<br />place: San Diego County, CA<br />place: San Diego County, CA\",\"year: 2014<br />value:  7.0<br />place: San Diego County, CA<br />place: San Diego County, CA\",\"year: 2015<br />value:  7.1<br />place: San Diego County, CA<br />place: San Diego County, CA\",\"year: 2016<br />value:  7.3<br />place: San Diego County, CA<br />place: San Diego County, CA\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(127,211,78,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"San Diego County, CA\",\"legendgroup\":\"San Diego County, CA\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1,4],\"y\":[2.6000000000000001,3.7999999999999998],\"text\":[\"year: 2010<br />value:  2.6<br />place: San Francisco, CA<br />place: San Francisco, CA\",\"year: 2013<br />value:  3.8<br />place: San Francisco, CA<br />place: San Francisco, CA\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(151,216,63,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"San Francisco, CA\",\"legendgroup\":\"San Francisco, CA\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[2,3,4],\"y\":[5.9000000000000004,6.0999999999999996,7.0999999999999996],\"text\":[\"year: 2011<br />value:  5.9<br />place: San Jose, CA<br />place: San Jose, CA\",\"year: 2012<br />value:  6.1<br />place: San Jose, CA<br />place: San Jose, CA\",\"year: 2013<br />value:  7.1<br />place: San Jose, CA<br />place: San Jose, CA\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(177,221,46,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"San Jose, CA\",\"legendgroup\":\"San Jose, CA\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1,2,3,4,5],\"y\":[3.8999999999999999,2.8999999999999999,5.2000000000000002,3,3.6000000000000001],\"text\":[\"year: 2010<br />value:  3.9<br />place: Seattle, WA<br />place: Seattle, WA\",\"year: 2011<br />value:  2.9<br />place: Seattle, WA<br />place: Seattle, WA\",\"year: 2012<br />value:  5.2<br />place: Seattle, WA<br />place: Seattle, WA\",\"year: 2013<br />value:  3.0<br />place: Seattle, WA<br />place: Seattle, WA\",\"year: 2014<br />value:  3.6<br />place: Seattle, WA<br />place: Seattle, WA\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(203,225,30,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Seattle, WA\",\"legendgroup\":\"Seattle, WA\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1,2,3,4,5,6],\"y\":[11.300000000000001,11.1,11.4,10.9,10.800000000000001,11.4],\"text\":[\"year: 2010<br />value: 11.3<br />place: U.S. Total, U.S. Total<br />place: U.S. Total, U.S. Total\",\"year: 2011<br />value: 11.1<br />place: U.S. Total, U.S. Total<br />place: U.S. Total, U.S. Total\",\"year: 2012<br />value: 11.4<br />place: U.S. Total, U.S. Total<br />place: U.S. Total, U.S. Total\",\"year: 2013<br />value: 10.9<br />place: U.S. Total, U.S. Total<br />place: U.S. Total, U.S. Total\",\"year: 2014<br />value: 10.8<br />place: U.S. Total, U.S. Total<br />place: U.S. Total, U.S. Total\",\"year: 2015<br />value: 11.4<br />place: U.S. Total, U.S. Total<br />place: U.S. Total, U.S. Total\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(229,228,25,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"U.S. Total, U.S. Total\",\"legendgroup\":\"U.S. Total, U.S. Total\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1,2,3],\"y\":[5.5999999999999996,5.4000000000000004,6.5999999999999996],\"text\":[\"year: 2010<br />value:  5.6<br />place: Washington, DC<br />place: Washington, DC\",\"year: 2011<br />value:  5.4<br />place: Washington, DC<br />place: Washington, DC\",\"year: 2012<br />value:  6.6<br />place: Washington, DC<br />place: Washington, DC\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(253,231,37,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Washington, DC\",\"legendgroup\":\"Washington, DC\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":43.762557077625573,\"r\":7.3059360730593621,\"b\":40.182648401826498,\"l\":37.260273972602747},\"plot_bgcolor\":\"rgba(255,255,255,1)\",\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"title\":{\"text\":\"Motor Vehicle Fatality Rates by City\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":17.534246575342465},\"x\":0,\"xref\":\"paper\"},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[0.40000000000000002,7.5999999999999996],\"tickmode\":\"array\",\"ticktext\":[\"2010\",\"2011\",\"2012\",\"2013\",\"2014\",\"2015\",\"2016\"],\"tickvals\":[1,2,3,4.0000000000000009,5,6,7],\"categoryorder\":\"array\",\"categoryarray\":[\"2010\",\"2011\",\"2012\",\"2013\",\"2014\",\"2015\",\"2016\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.66417600664176002,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"Year\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[2.0550000000000002,14.045],\"tickmode\":\"array\",\"ticktext\":[\"5\",\"10\"],\"tickvals\":[5,10],\"categoryorder\":\"array\",\"categoryarray\":[\"5\",\"10\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.66417600664176002,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Fatality (death/100,000 population)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":\"transparent\",\"line\":{\"color\":\"rgba(51,51,51,1)\",\"width\":0.66417600664176002,\"linetype\":\"solid\"},\"yref\":\"paper\",\"xref\":\"paper\",\"layer\":\"below\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":true,\"legend\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":1.8897637795275593,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":7.9701120797011207},\"title\":{\"text\":\"place\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":10.62681610626816}}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"433a4e10e1f1\":{\"x\":{},\"y\":{},\"colour\":{},\"type\":\"scatter\"}},\"cur_data\":\"433a4e10e1f1\",\"visdat\":{\"433a4e10e1f1\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\nIsn't this amazing? I'm blown away that one additional line of code did all that.\n\n### Faceting\n\nOk, one last trick. Say we wanted to give each city its own little plot to understand time-trends within the city. We can certainly get this information from the spaghetti plot but it would undoubtedly cause a headache. Let's play with `facet_wrap` and `facet_grid` instead.\n\nThe difference between these two isn't super clear to start with, but basically, `facet_wrap` is good if you're just faceting on one variable (in our case, city). If you want to end up with a separate mini-plot for each combination of two variables (for instance, a mini-plot for female fatalities in Denver, another plot for male fatalities in Denver, and so on for every combination of city and sex), you want `facet_grid` (more info [here](https://ggplot2-book.org/facet.html)).\n\nWe're going to start with `facet_wrap`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrive_df %>% \n  filter(sex == \"Both\", race_ethnicity == \"All\") %>% \n  ggplot(aes(x = year, y = value, group = place)) + \n  geom_line() + \n  facet_wrap(vars(place))\n```\n\n::: {.cell-output-display}\n![](car-crashes_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\nAside from the fact that the x-axis labels are a bit messed up, this is actually pretty nice.\n\nNow let's try a grid for combinations of place and sex.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrive_df %>% \n  filter(!sex == \"Both\", race_ethnicity == \"All\") %>% \n  ggplot(aes(x = year, y = value, group = place)) + \n  geom_line() + \n  facet_grid(sex ~ place)\n```\n\n::: {.cell-output-display}\n![](car-crashes_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\nLet's go back to `facet_wrap` and just do some color-coding for sex rather than trying to make sense of this crazy grid.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrive_df %>% \n  filter(!sex == \"Both\", race_ethnicity == \"All\") %>% \n  ggplot(aes(x = year, y = value, group = sex)) + \n  geom_line(aes(color = sex)) + \n  facet_wrap(vars(place))\n```\n\n::: {.cell-output-display}\n![](car-crashes_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\nIf we fix the formatting, this will actually be an ok plot. First off, we should minimize the number of plots displayed horizontally using `ncol`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrive_df %>% \n  filter(!sex == \"Both\", race_ethnicity == \"All\") %>% \n  ggplot(aes(x = year, y = value, group = sex)) + \n  geom_line(aes(color = sex)) + \n  facet_wrap(vars(place), ncol = 3)\n```\n\n::: {.cell-output-display}\n![](car-crashes_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\nNext, let's fix up the colors, axes, legend, etc.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrive_df %>% \n  filter(!sex == \"Both\", race_ethnicity == \"All\") %>% \n  ggplot(aes(x = year, y = value, group = sex)) + \n  geom_line(aes(color = sex)) + \n  scale_color_manual(values=c(\"#996699\", \"#99CC99\")) +\n  facet_wrap(vars(place), ncol = 3)  + \n    theme_bw() +\n    labs(\n      title = \"Motor Vehicle Fatality Rate 2010-2016 by Sex\",\n      x = \"Year\",\n      y = \"Fatality (death/100,000 population)\",\n      caption = \"Data source: Big Cities Health Initiative\"\n    )\n```\n\n::: {.cell-output-display}\n![](car-crashes_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\nIt's clear we have an issue with Indianapolis (perhaps they only provide the combined male/female figure but not the individual values). It's also clear that Boston had only 2 years of data and other cities have some missing data as well. But a more interesting finding is comparing Denver to Detroit, which are conveniently side-by-side. Detroit saw a leveling off, whereas Denver saw a sharp increase in male fatalities. San Jose sticks out, too, as the only city where female fatalities surpassed male fatalities (and sharply so...) If I were an analyst looking at traffic safety, I'd put some focus on Denver and San Jose and figure out what's going on there.\n\n## Conclusions\n\nI hope you agree that we learned a bit about car crash fatalities. My takeaways were: - There is a huge disparity between male and female motor vehicle fatalities in nearly every big city in the U.S., males experiencing double and sometimes triple the female average fatality rate. - Detroit has historically had the highest burden of motor vehicle fatalities, but Denver has recently caught up. - `ggplot2` is a great tool. `ggplotly` is even better.\n\nThis is absolutely just a surface-scratch of all the things `ggplot2` can do, so please take a look at the links below for more complete package exploration.\n\n## Further Reading\n\n-   A handy [cheat sheet](https://rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf)\n-   A beautiful [collection](https://www.r-graph-gallery.com/index.html) of R data viz inspiration\n\n## References\n\n-   Michonneau F, Teal T, Fournier A, Seok B, Obeng A, Pawlik AN, Conrado AC, Woo K, Lijnzaad P, Hart T, White EP, Marwick B, Bolker B, Jordan KL, Ashander J, Dashnow H, Hertweck K, Cuesta SM, Becker EA, Guillou S, Shiklomanov A, Klinges D, Odom GJ, Jean M, Mislan KAS, Johnson K, Jahn N, Mannheimer S, Pederson S, Pletzer A, Fouilloux A, Switzer C, Bahlai C, Li D, Kerchner D, Rodriguez-Sanchez F, Rajeg GPW, Ye H, Tavares H, Leinweber K, Peck K, Lepore ML, Hancock S, Sandmann T, Hodges T, Tirok K, Jean M, Bailey A, von Hardenberg A, Theobold A, Wright A, Basu A, Johnson C, Voter C, Hulshof C, Bouquin D, Quinn D, Vanichkina D, Wilson E, Strauss E, Bledsoe E, Gan E, Fishman D, Boehm F, Daskalova G, Tavares H, Kaupp J, Dunic J, Keane J, Stachelek J, Herr JR, Millar J, Lotterhos K, Cranston K, Direk K, Tylén K, Chatzidimitriou K, Deer L, Tarkowski L, Chiapello M, Burle M, Ankenbrand M, Czapanskiy M, Moreno M, Culshaw-Maurer M, Koontz M, Weisner M, Johnston M, Carchedi N, Burge OR, Harrison P, Humburg P, Pauloo R, Peek R, Elahi R, Cortijo S, sfn_brt, Umashankar S, Goswami S, Sumedh, Yanco S, Webster T, Reiter T, Pearse W, Li Y (2020). “datacarpentry/R-ecology-lesson: Data Carpentry: Data Analysis and Visualization in R for Ecologists, June 2019.” doi: 10.5281/zenodo.3264888, <https://datacarpentry.org/R-ecology-lesson/.>\n",
    "supporting": [
      "car-crashes_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"../../site_libs/plotly-binding-4.11.0/plotly.js\"></script>\n<script src=\"../../site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"../../site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"../../site_libs/crosstalk-1.2.1/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/crosstalk-1.2.1/js/crosstalk.min.js\"></script>\n<link href=\"../../site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}